### ISSUE TITLE
Undefined index: aggregations

### ISSUE THREAD

**Issue by kiwo12345** [adamfairholm/Elasticquent#18]
When I try to use search() I get the error: Undefined index: aggregations

Line 26 in /vendor/fairholm/elasticquent/src/ElasticquentResultCollection.php
$this->aggregations = $results['aggregations'];

**Comment by kiwo12345** [comment]
If I comment out "$this->aggregations = $results['aggregations'];" everything works.

Anyhow, I followed this tutorial:
http://www.fullstackstanley.com/read/simple-search-with-laravel-and-elasticsearch

**Comment by adamfairholm** [comment]
Hi @kiwo12345 - have you pulled in the latest version? This should commit should have fixed this error:

https://github.com/adamfairholm/Elasticquent/commit/177914a2388a654dbdb53d91668249392b76c9f1

**Comment by Artistan** [comment]
still  not accessible in composer, need to tag fix and update packagist?

**Comment by timgws** [comment]
@Artistan, yes.

You could switch to `dev-master`, or alternatively, take a look at https://github.com/elasticquent/Elasticquent, which is a fork of this repository that I have started maintaining.

**Comment by adamfairholm** [comment]
Hi @timgws - that fork looks great - I wonder if there is a smooth way to make that the official Elasticquent version instead of my version - I took a job shortly after releasing the initial version of this and just haven't haven't had the time to do any maintenance. I also like the elasticquent/elasticquent namespace.
